// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLCHBanAo.Models;

#nullable disable

namespace QLCHBanAo.Migrations
{
    [DbContext(typeof(QlbaDbContext))]
    [Migration("20251116174535_KhoiTaoCSDL1")]
    partial class KhoiTaoCSDL1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLCHBanAo.Models.BienThe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BienTheHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChatLieuId")
                        .HasColumnType("int");

                    b.Property<int>("ChatLieu_ID")
                        .HasColumnType("int");

                    b.Property<int>("Color_ID")
                        .HasColumnType("int");

                    b.Property<int>("KichThuocId")
                        .HasColumnType("int");

                    b.Property<int>("MauSacId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SanPham_ID")
                        .HasColumnType("int");

                    b.Property<int>("Size_ID")
                        .HasColumnType("int");

                    b.Property<int>("ThuongHieuId")
                        .HasColumnType("int");

                    b.Property<int>("ThuongHieu_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatLieuId");

                    b.HasIndex("KichThuocId");

                    b.HasIndex("MauSacId");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("ThuongHieuId");

                    b.ToTable("BienThe", (string)null);
                });

            modelBuilder.Entity("QLCHBanAo.Models.ChatLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatLieu", (string)null);
                });

            modelBuilder.Entity("QLCHBanAo.Models.CuaHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CuaHang", (string)null);
                });

            modelBuilder.Entity("QLCHBanAo.Models.KichThuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenKichThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KichThuoc", (string)null);
                });

            modelBuilder.Entity("QLCHBanAo.Models.MauSac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MauSac", (string)null);
                });

            modelBuilder.Entity("QLCHBanAo.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuyenHan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLCHBanAo.Models.NguoiDungCuaHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuaHangId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuaHangId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NguoiDungCuaHang", (string)null);
                });

            modelBuilder.Entity("QLCHBanAo.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("QLCHBanAo.Models.ThuongHieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThuongHieu", (string)null);
                });

            modelBuilder.Entity("QLCHBanAo.Models.TonKhoSP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienTheId")
                        .HasColumnType("int");

                    b.Property<int>("BienThe_ID")
                        .HasColumnType("int");

                    b.Property<int>("CuaHangId")
                        .HasColumnType("int");

                    b.Property<int>("CuaHang_ID")
                        .HasColumnType("int");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BienTheId");

                    b.HasIndex("CuaHangId");

                    b.ToTable("TonKhoSP", (string)null);
                });

            modelBuilder.Entity("QLCHBanAo.Models.BienThe", b =>
                {
                    b.HasOne("QLCHBanAo.Models.ChatLieu", "ChatLieu")
                        .WithMany("BienThe")
                        .HasForeignKey("ChatLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLCHBanAo.Models.KichThuoc", "KichThuoc")
                        .WithMany("BienThe")
                        .HasForeignKey("KichThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLCHBanAo.Models.MauSac", "MauSac")
                        .WithMany("BienThe")
                        .HasForeignKey("MauSacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLCHBanAo.Models.SanPham", "SanPham")
                        .WithMany("BienThe")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLCHBanAo.Models.ThuongHieu", "ThuongHieu")
                        .WithMany("BienThe")
                        .HasForeignKey("ThuongHieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("KichThuoc");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("QLCHBanAo.Models.NguoiDungCuaHang", b =>
                {
                    b.HasOne("QLCHBanAo.Models.CuaHang", "CuaHang")
                        .WithMany("NguoiDungCuaHang")
                        .HasForeignKey("CuaHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLCHBanAo.Models.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungCuaHang")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuaHang");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QLCHBanAo.Models.TonKhoSP", b =>
                {
                    b.HasOne("QLCHBanAo.Models.BienThe", "BienThe")
                        .WithMany("TonKhoSP")
                        .HasForeignKey("BienTheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLCHBanAo.Models.CuaHang", "CuaHang")
                        .WithMany("TonKhoSP")
                        .HasForeignKey("CuaHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienThe");

                    b.Navigation("CuaHang");
                });

            modelBuilder.Entity("QLCHBanAo.Models.BienThe", b =>
                {
                    b.Navigation("TonKhoSP");
                });

            modelBuilder.Entity("QLCHBanAo.Models.ChatLieu", b =>
                {
                    b.Navigation("BienThe");
                });

            modelBuilder.Entity("QLCHBanAo.Models.CuaHang", b =>
                {
                    b.Navigation("NguoiDungCuaHang");

                    b.Navigation("TonKhoSP");
                });

            modelBuilder.Entity("QLCHBanAo.Models.KichThuoc", b =>
                {
                    b.Navigation("BienThe");
                });

            modelBuilder.Entity("QLCHBanAo.Models.MauSac", b =>
                {
                    b.Navigation("BienThe");
                });

            modelBuilder.Entity("QLCHBanAo.Models.NguoiDung", b =>
                {
                    b.Navigation("NguoiDungCuaHang");
                });

            modelBuilder.Entity("QLCHBanAo.Models.SanPham", b =>
                {
                    b.Navigation("BienThe");
                });

            modelBuilder.Entity("QLCHBanAo.Models.ThuongHieu", b =>
                {
                    b.Navigation("BienThe");
                });
#pragma warning restore 612, 618
        }
    }
}
